@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}

class Resource  <<Pivot>> {
    category : String
    description : String
    endOperatingDate : DateTime
    href : String [1]
    id : String [1]
    lifecycleState : ResourceLifecycleStateType
    lifecycleSubState : ResourceLifecycleSubStateType
    manufactureDate : DateTime
    name : String [1]
    powerState : String
    resourceVersion : String
    serialNumber : String
    startOperatingDate : DateTime
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ResourceLifecycleStateType <<Enumeration>> {
    planning
    installing
    operating
    retiring
}

class ResourceLifecycleSubStateType <<Enumeration>> {
    proposed
    feasibility checked
    designed
    ordered
    activated
    deactivated
    working
    working meets all SLAs
    working meets some SLAs
    working meets no SLA
    not working
    available
    not available
    assigned
    reserved
}

class Note  {
    author : String
    date : DateTime
    text : String [1]
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ResourceSpecificationRef  <<Ref>> {
    href : String [1]
    id : String [1]
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class Characteristic  {
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedPartyRef  <<Ref>> {
    href : String
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class PartyRoleRef  <<Ref>> {
    href : String [1]
    id : String [1]
    name : String
    partyId : String
    partyName : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ResourceRelationship  {
    name : String
    type : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ResourceRef  <<Ref>> {
    href : String
    id : String [1]
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class PlaceRef  <<Ref>> {
    href : String
    id : String [1]
    name : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

Resource -right[hidden]-> ResourceLifecycleStateType

ResourceLifecycleStateType -right[hidden]-> ResourceLifecycleSubStateType

Resource *-->  "0..*" Characteristic : resourceCharacteristic

Resource *-->  "0..*" ResourceRelationship : resourceRelationship

ResourceRelationship *-right-> "0..*" Characteristic : resourceRelationshipCharacteristic

Note "0..*" <-left-* Resource : note

PlaceRef "0..1" <--* Resource : place

PartyRoleRef "0..*" <--* Resource : partyRole

RelatedPartyRef "0..*" <--* Resource : relatedParty

Resource *-->  "0..1" ResourceSpecificationRef : resourceSpecification

Characteristic <-left[hidden]- ResourceSpecificationRef

ResourceRelationship *-->  "0..1" ResourceRef : resourceRef

@enduml