@startuml
hide circle
hide methods
hide stereotype
show <<Enumeration>> stereotype
skinparam class {
   BackgroundColor<<Enumeration>> #E6F5F7
   BackgroundColor<<Ref>> #FFFFE0
   BackgroundColor<<Pivot>> #FFFFFFF
   BackgroundColor #FCF2E3
}

class PhysicalResource  <<Pivot>> {
    category : String
    description : String
    endOperatingDate : DateTime
    href : String [1]
    id : String [1]
    lifecycleState : ResourceLifecycleStateType
    manufactureDate : DateTime
    name : String
    powerState : String
    resourceVersion : String
    serialNumber : String
    startOperatingDate : DateTime
    versionNumber : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedPlaceRefOrValue  {
    href : String [1]
    id : String [1]
    name : String
    role : String [1]
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class AttachmentRefOrValue  {
    attachmentType : String
    content : String
    description : String
    href : String
    id : String
    mimeType : String
    name : String
    size : Quantity
    url : String
    validFor : TimePeriod
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class Note  {
    author : String
    date : DateTime
    text : String [1]
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ResourceSpecificationRef  <<Ref>> {
    href : String [1]
    id : String [1]
    name : String
    version : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class Characteristic  {
    name : String [1]
    value : Any [1]
    valueType : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class RelatedPartyRef  <<Ref>> {
    href : String
    id : String [1]
    name : String
    role : String
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

class ResourceRelationship  {
    name : String
    type : String
    @baseType : String
    @schemaLocation : Uri
    @type : String
}

class ResourceRef  <<Ref>> {
    href : String
    id : String [1]
    @baseType : String
    @referredType : String
    @schemaLocation : Uri
    @type : String
}

PhysicalResource -right[hidden]-> ResourceLifecycleStateType

PhysicalResource *-->  "0..*" Characteristic : resourceCharacteristic

PhysicalResource *-->  "0..*" ResourceRelationship : resourceRelationship

ResourceRelationship *-right-> "0..*" Characteristic : resourceRelationshipCharacteristic

Note "0..*" <-left-* PhysicalResource : note

RelatedPartyRef "0..*" <--* PhysicalResource : relatedParty

RelatedPlaceRefOrValue "0..1" <--* PhysicalResource : relatedPlace

AttachmentRefOrValue "0..*" <--* PhysicalResource : resourceAttachment

PhysicalResource *-->  "0..1" ResourceSpecificationRef : resourceSpecification

Characteristic <-left[hidden]- ResourceSpecificationRef

ResourceRelationship *-->  "0..1" ResourceRef : resourceRef

@enduml